server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888
zuul:
  routes:
    passwordmeter-backend:
      path: /api/**
      stripPrefix: true
    passwordmeter-front:
      path: /**
      stripPrefix: false